import App from './GopherList.svelte';
import Header from './HeaderZone.svelte';
import AddGopher from './AddGopher.svelte';
import ReadMe from "./ReadMe.svelte";
import FooterZone from "./FooterZone.svelte";
import EditGopher from "./EditGopher.svelte";
import EditRequest from "./EditRequest.svelte";
import LoginArea from "./LoginArea.svelte";
import DashboardZone from "./DashboardZone.svelte";